export const METHODS = {
    JOIN_ROOM: 'JOIN_ROOM',
    START_GAME: 'START_GAME',
    MAKE_MOVE: 'MAKE_MOVE',
    UPDATE_GAME: 'UPDATE_GAME',
    UPDATE_PLAYERS: 'UPDATE_PLAYERS',
    RESTART_GAME: 'RESTART_GAME',
    OPPONENT_LEFT: 'OPPONENT_LEFT',
    ERROR: 'ERROR'
};

export const GAME_STATUS = {
    PLAYING: 'PLAYING',
    FINISHED: 'FINISHED'
};